<?php 
session_start();
session_unset();
session_destroy();
header ('location : page.php')
?>

<!--
TODO :: 1 - FAIRE DES SESSIONS
2 - RELIER PAR POST LE FORMULAIRE D'INSCRIPTION AVEC CELUI DE CONNEXION
3 - DIRE QUE LES VARIABLE MAIL ET MDP DE INSCRIPTION SONT CELLES DE LOGIN ET PASSEWORD
4 - DIRE QUE DONC ON UTILISE QUE LA BDD INSCRIPTION
5 - DIRE SI MAIL ET MDP EXISTENT ET S'ILS SONT RENSEIGNE 
6 - ENVOYER VERS OU UNE FOIS L'INSCRIPTION FAITE ? ON ENVOIE VERS UNE NOUVELLE PAGE OU VERS COMMANDE COMME SI ON SE CONNECTAIS ? OU COMME SI ON SE CONNECTAIS ET DONC LA ON AURAIT QUAND MEME UNE PETITE LIGNE POUR NOUS DIRE QU'ON EST BIEN CONNECTE ?
7 - SESSION START LE METTRE DANS TOUTES LES PAGES OU PAS ?
8 - OU METTRE ET NE PAS OUBLIER DE METTRE LE SESSION DESTROY, GENRE FAIRE UN BOUTON DECONNEXION DE PARTOUT VIA UN INCLUDE ? -->